server:
  port: ${PORT:5000}

base-url: /api

spring:
  profiles:
    active:
      ${APP_ENV}
  application:
    name: taskManager

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml

  jpa:
    hibernate:
      ddl-auto: create-drop
