server:
  port: ${PORT:5000}

logging:
  level:
    root: INFO

spring:
  default: ${APP_ENV}
  development:
    username: sa
    password:
    url: "jdbc:h2:./taskManagerDb"
  production:
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    url: ${JDBC_DATABASE_URL}

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml

  jpa:
    hibernate:
      ddl-auto: create-drop

  h2:
    console:
      enabled: true
      path: /h2console/
      settings:
        web-allow-others: true
